server:
    port: 8030
spring:
    application:
        name: EPDMS-CONFIGURATION-SERVICE
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/mahesh10061991/epdms-configuration-service
                    clone-on-start: true
                    default-label: main
                    username: mahesh10061991
                    password: ghp_ybM8NE1mAp5V7GIrZCGcgiChXTRxfR0sdfsd
                    # skipSslValidation: true
                    # timeout: 4
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
